export const MessageDetail = () => {
    return (
        <div className='max-h-[calc(100dvh-175px)] lg:max-h-[calc(100dvh-179px)] h-[100dvh] flex-1 overflow-y-scroll scrollbar'>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>MessageDetail</p>
            <p>123123123131231312</p>
        </div>
    )
}
